### ISSUE TITLE
`thunked` function: why `tid` is an object, but everywhere else it is a function?

### ISSUE THREAD

**Issue by srghma** [purescript-halogen/purescript-halogen-vdom#35]
why here `tid` is an object with a render function

https://github.com/purescript-halogen/purescript-halogen-vdom/blob/8b91e55019060f50779dba20959f47cf4b60678d/src/Halogen/VDom/Thunk.purs#L51

but everywhere else it is just a render function?

https://github.com/purescript-halogen/purescript-halogen-vdom/blob/8b91e55019060f50779dba20959f47cf4b60678d/src/Halogen/VDom/Thunk.purs#L57

**Comment by natefaubion** [comment]
The intention is that it creates a unique reference, so that one application of function and equality is only ever equal to itself. It forces you into using it a certain way which makes it more stable by creating a binding, due to how the compiler generalizes (or doesn't). The other ones don't take an arbitrary equality, it's fixed ahead of time in a stable way by the library, so calling them inline is usually intuitive. But for example, if you just called `memoize` (from Halogen or Spork which uses `thunked`) inline with an `eq`:
* Something like `Eq String` would be OK, since it always returns the same dictionary, and thus the same `eq` function.
* Something like `Eq (Array String)` probably would not be OK, since it creates a new dictionary on the fly parameterized by `String`, and you'd get a unique reference each time it's called.

This is very difficult to reason about because their are no referential semantics for dictionaries. Instead of trying to explain the subtleties here, it just _forces_ you to apply these in a binding, and refer to that binding.

**Comment by srghma** [comment]
@natefaubion yes, but why `unsafeThunkId { f }`, why not `unsafeThunkId f` (which is done like this everywhere else)?

**Comment by natefaubion** [comment]
The object wrapper is what creates the unique reference, it's a fresh object that no one else as a reference to except the internal thunk.

**Comment by srghma** [comment]
ok, kind of understand, it's an additional safety check

you are kind of saying `you cannot use refEq function here, it will always return false`

----

one more question

why I don't see the equality function, that is stored inside of thunk (`(Fn.Fn2 ThunkArg ThunkArg Boolean)`) is used anywhere in this file?

https://github.com/purescript-halogen/purescript-halogen-vdom/blob/master/src/Halogen/VDom/Thunk.purs

the only place I see it is here 

https://github.com/purescript-halogen/purescript-halogen-vdom/blob/8b91e55019060f50779dba20959f47cf4b60678d/src/Halogen/VDom/Thunk.purs#L86

but it is not being called

**Comment by srghma** [comment]
now understand everything, will close
